Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -12,9 +12,8 @@ jobs:
     steps:
       - name: Failed step
         run: | 
-          echo "I"
-          echo "Will"
-          echo "Fail"
+          echo "I will fail"
+          exit 1
       - name: Say goodbye
         run: echo "Goodbye!"
       
